export const DILUTION_MAP: Record<string, number> = {
  '100%': 1,
  '50%': 0.5,
  '20%': 0.2,
  '10%': 0.1,
  '5%': 0.05,
  '1%': 0.01,
  '0.1%': 0.001
};

export const IFRA_LIMITS: Record<string, number> = {
  // --- A ---
  "Abietic acid": 0,
  "Acetic acid, anhydride": 2.4,
  "Acorus calamus oil": 0,
  "Alantroot oil": 0,
  "Allyl 3-cyclohexylpropionate": 0.47,
  "Allyl heptine carbonate": 0,
  "Allyl isothiocyanate": 0,
  "Allyl phenoxyacetate": 0.3,
  "alpha-Amyl cinnamic alcohol": 1.5,
  "alpha-Amyl cinnamic aldehyde": 7,
  "alpha-Amyl cinnamic aldehyde diethyl acetal": 0.35,
  "alpha-Amyl cinnamic aldehyde dimethyl acetal": 0.35,
  "alpha-Bisabolol": 2.4,
  "alpha-Butylcinnamaldehyde": 0.43,
  "alpha-Cyclohexylidene benzeneacetonitrile": 0.52,
  "alpha-Hexyl cinnamic aldehyde": 9.9,
  "alpha-Hexylidene cyclopentanone": 0.13,
  "alpha-Methyl cinnamic aldehyde": 1.5,
  "alpha-Methyl anisylidene acetone": 0,
  "alpha,2,2,3-Tetramethylcyclopent-3-ene-1-butyraldehyde": 0.21,
  "Amylcyclopentenone": 0,
  "Angelica root oil": 0.8,
  "Anisyl alcohol": 0.21,
  "Anisylidene acetone": 0,
  "Asarone": 0,

  // --- B ---
  "Bacdanol": 1.2,
  "Benzaldehyde": 0.25,
  "Benzene": 0,
  "Benzyl alcohol": 2.5,
  "Benzyl benzoate": 4.8,
  "Benzyl cinnamate": 2,
  "Benzyl cyanide": 0,
  "BENZYL SALICYILATE": 7.3,
  "Benzylidene acetone": 0,
  "Bergamot oil expressed": 0.4,
  "Birch wood pyrolysate": 0,
  "Bitter orange peel oil expressed": 1.25,
  "Boldo oil": 0,
  "Bourgeonal": 0.47,
  "Brahmanol": 1.2,
  "3-Bromo-1,7,7-trimethylbicyclo[2.2.1]heptan-2-one": 0,
  "Bromostyrene": 0,
  "p-tert-Butylphenol": 0,
  "4-tert-Butylcyclohexanone": 0.15,

  // --- C ---
  "Cade oil": 0,
  "Carvone": 0.59,
  "Carvone oxide": 0,
  "Carvomenthone": 1.9,
  "Carvyl acetate": 0.24,
  "Cashmeran": 3.8,
  "Cedrene": 1.5,
  "Chenopodium oil": 0,
  "Cinnamic alcohol": 1.2,
  "Cinnamic aldehyde": 0.25,
  "Cinnamic aldehyde dimethyl acetal": 0.35,
  "Cinnamylidene acetone": 0,
  "Cinnamyl nitrile": 0.43,
  "Citral": 0.6,
  "Citronellal": 0.49,
  "Citronellol": 12,
  "Citronellyl acetate": 2.7,
  "Colophony": 0,
  "Costus root oil": 0,
  "Coumarin": 1.5,
  "Creosol": 0.047,
  "Cuminaldehyde": 0.47,
  "Cumin oil": 0.4,
  "Cyclamen alcohol": 0,
  "Cyclamen aldehyde": 0.95,
  "Cyclohexadecanone": 4.3,
  "Cyclohexadecenone": 4.3,

  // --- D ---
  "2,4-Decadienal": 0.02,
  "Dibenzyl ether": 0.012,
  "2,2-Dichloro-1-methylcyclopropylbenzene": 0,
  "Diethyl maleate": 0,
  "Dihydrocoumarin": 0.21,
  "2,4-Dihydroxy-3-methylbenzaldehyde": 0,
  "Dimethyl citraconate": 0,
  "Dimethyl octenone": 1.9,
  "3,7-Dimethyl-2,6-nonadien-1-al": 0.6,
  "5,9-Dimethyl-4,8-decadienal": 3,
  "3,7-Dimethyl-3,6-octadienal": 3,
  "4,8-Dimethyl-4,9-decadienal": 0.24,
  "4,6-Dimethyl-8-tert-butylcoumarin": 0,
  "3,7-Dimethyl-2-octen-1-ol": 0,
  "Diphenylamine": 0,
  "2,4-Dodecadien-1-ol": 0.02,

  // --- E ---
  "Estragole": 0.014,
  "2-Ethoxy-4-methylphenol": 0.099,
  "Ethyl acrylate": 0,
  "p-Ethylbenzaldehyde": 0.47,
  "Ethylene glycol monoethyl ether": 0,
  "Ethylene glycol monomethyl ether": 0,
  "Ethyl isopropyl bicycloheptene-2-carboxylate": 0.94,
  "Ethyl furaneol": 0.25,
  "Eugenol": 2.5,

  // --- F ---
  "Farnesal": 0.6,
  "Farnesol": 1.2,
  "Fig leaf absolute": 0.02,
  "Floralozone": 1.1,
  "Furfural": 0.001,
  "Furfuryl alcohol": 0,
  "Furfurylidene acetone": 0,

  // --- G ---
  "Geraniol": 4.7,
  "Geranyl nitrile": 0,
  "Grapefruit oil expressed": 4,

  // --- H ---
  "Helional": 2.6,
  "trans-2-Heptenal": 0.02,
  "2-Heptylidene cyclopentan-1-one": 0.43,
  "cis-3-Heptenyl acetate": 0.43,
  "Hexahydrocoumarin": 0,
  "2,4-Hexadien-1-ol": 0,
  "2-Hexenal": 0.0077,
  "cis-3-Hexenyl isovalerate": 0.43,
  "cis-3-Hexenyl methyl carbonate": 0.56,
  "2-Hexylidenecyclohexan-1-one": 0.13,
  "Hexyl salicylate": 6.5,
  "Hydroabietyl alcohol": 0,
  "Hydroxycitronellal": 2.1,

  // --- I ---
  "Iso E Super": 20,
  "Isobutyl cinnamate": 1.2,
  "Isocyclocitral": 3,
  "Isocyclogeraniol": 1.6,
  "Isoeugenol": 0.11,
  "Isoeugenyl acetate": 0.99,
  "Isopentylcyclohexanone": 0.15,
  "Isophorone": 0,
  "6-Isopropyl-2-decalol": 0,
  "Isopropylcyclohexanemethanol": 4.7,
  "Isopropyl methylcyclohexanethanol": 6.4,
  "p-Isopropylbenzyl alcohol": 2.5,

  // --- J / L ---
  "Jasmine absolute (grandiflorum)": 0.6,
  "Jasmine absolute (sambac)": 3.8,
  "Koavone": 1.9,
  "Lemon oil cold pressed": 2,
  "Lilial": 0,
  "Lime oil expressed": 0.7,
  "Linalool": 100,
  "Limonene": 100,
  "Longifolene": 1.5,
  "Lyral": 0.2,

  // --- M ---
  "Majantol": 1.7,
  "Massoia bark oil": 0,
  "Massoia lactone": 0,
  "Melissa oil": 0.6,
  "Menthadiene-7-methyl formate": 0.43,
  "p-Methoxybenzaldehyde": 1.4,
  "o-Methoxycinnamaldehyde": 0.43,
  "Methoxy dicyclopentadiene carboxaldehyde": 1.1,
  "4-Methoxy-alpha-methylbenzenepropanal": 2.5,
  "Methyl beta-naphthyl ketone": 0.2,
  "Methyl crotonate": 0,
  "Methyl eugenol": 0.011,
  "Methyl furaneol": 0.25,
  "Methyl heptine carbonate": 0.047,
  "Methyl ionone, mixed isomers": 30,
  "Methyl lavender ketone": 0.082,
  "Methyl methacrylate": 0,
  "Methyl N-methylanthranilate": 0.1,
  "Methyl octine carbonate": 0.01,
  "p-Methylhydrocinnamic aldehyde": 0,
  "Methyl vanillyl ether": 1.5,
  "Mintlactone": 0,
  "Musk alpha": 0,
  "Musk ambrette": 0,
  "Musk KS": 0,
  "Musk moskene": 0,
  "Musk tibetene": 0,
  "Musk xylene": 0,
  "Myraldyl acetate": 0.43,

  // --- N ---
  "Nitrobenzene": 0,
  "2-Nonyn-1-al dimethyl acetal": 9.9,
  "cis-3-Nonenyl acetate": 0.43,

  // --- O ---
  "Oakmoss extracts": 0.1,
  "Octahydro-dimethylnaphthalene-2-carbaldehyde": 2.1,
  "1-Octen-3-yl acetate": 1.5,
  "2-Octen-4-one": 0.047,
  "2,5-Octadien-4-one, 5,6,7-trimethyl-": 0.11,
  "Opoponax": 0.43,
  "OTNE": 20,

  // --- P ---
  "2-Pentylidene cyclohexanone": 0,
  "Perilla aldehyde": 0.3,
  "Peru balsam": 0.41,
  "Phenoxyacetaldehyde": 0.25,
  "Phenyl acetone": 0,
  "Phenyl benzoate": 0,
  "Phenylacetaldehyde": 0.25,
  "Polysantol": 1.1,
  "Propenylguaethol": 0.99,
  "3-Propylidenephthalide": 0.4,
  "Pseudoionone": 0,
  "Pseudo methylionones": 0,

  // --- Q / R ---
  "Quinoline": 0,
  "Raspberry ketone": 1,
  "Rose ketones": 0.043,
  "Rue oil": 0.15,

  // --- S ---
  "Safrole": 0,
  "Safranal": 0.012,
  "Santolina oil": 0,
  "Savin oil": 0,
  "Styrax": 0.64,

  // --- T ---
  "Tagetes oil and absolute": 0.01,
  "Tea leaf absolute": 0.21,
  "Tetramethyl bicyclo-2-heptene-2-propionaldehyde": 1.3,
  "Thujone": 1.4,
  "Timberol": 1.5,
  "Toluene": 0,
  "Tolualdehydes": 0.47,
  "p-Tolyl alcohol": 1.5,
  "Treemoss extracts": 0.1,
  "Trifernal": 0.44,
  "Triplal": 2.5,

  // --- V / W / Y ---
  "Verbena oil and absolute": 0.69,
  "Woody furan": 0.94,
  "Ylang ylang extracts": 0.73,
  "Cis-3-Hexenol": 100,
  "Cis-3-Hexenyl acetate": 0.43,
  "Cis-3-Hexenyl salicylate": 6.5
};


export const FAMILY_COLORS: Record<string, string> = {
    "AGRUMATO": "#C3f53b",
    "AMBRATO": "#AB4502",
    "ANIMALICO": "#8B4513",
    "AROMATICO": "#2B5936",
    "BALSAMICO": "#6b2818",
    "CARAMELLO": "#CD853F",
    "CREMOSO": "#F5D678",
    "CIPRIATO": "#F5D789",
    "CUOIO": "#2e0e06",
    "LEGNOSO": "#381F0F",
    "MARINO": "#07108C",
    "FRUTTATO": "#FF2C00",
    "FLOREALE": "#B52F4A",
    "FLOREALE BIANCO": "#EDD5D8",
    "GOURMAND": "#c5c0c0",
    "FUMOSO": "#383737" , 
    "SALATO": "#F0F0F5",
    "SPEZIATO CALDO": "#822312",
    "SPEZIATO FRESCO": "#31A617",
    "ERBACEO": "#51824F",
    "FRESCO": "#91B5B5",
    "MUSCHIATO": "#D598FA",
    "VANIGLIATO": "#F5D793",
    "DOLCE": "#A82308",
    "RUM": "#591204",
    "ROSA": "#FC1729",
    "PATCHOULI": "#473F0C",
    "TROPICALE": "#E39102",
    "TERROSO": "#362C0A",
    "LATTONICO": "#EDE9E1",
    "OUD": "#302B17",
    "VERDE": "#0E9C09",
    "MELA": "#76E317",
    "MIELATO": "#F5AF00",
    "OZONICO": "#1DC4C4",
    "CIOCCOLATO": "#633D0D",
    "ACQUATICO": "#4061D6",
    "VIOLETTA": "#75014C",
    "CAFFE": "#593501",
};