export const DILUTION_MAP: Record<string, number> = {
  '100%': 1,
  '50%': 0.5,
  '20%': 0.2,
  '10%': 0.1,
  '5%': 0.05,
  '1%': 0.01,
  '0.1%': 0.001
};

export const MATERIALS_DB: Record<string, any> = {
  "TUBEROSA ACCORDO": {
    "CAS": "-",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0005,
    "BP": 290.0,
    "Impact": 350,
    "MinUsage": 0.5,
    "MaxUsage": 8.0,
    "AverageUsage": 3.0,
    "CostPerGram": 0.45,
    "Notes": "Fiorito bianco, narcotico",
    "Families": { "FLOREALE BIANCO": 100 },
    "Volatility": "Fondo"
  },
  "CASHMERAN": {
    "CAS": "33704-61-9",
    "Type": "Materia Prima",
    "IFRA": 3.8,
    "MinUsage": 0.1,
    "MaxUsage": 3.8,
    "AverageUsage": 2.0,
    "CostPerGram": 0.45,
    "Notes": "Muschiato, legnoso, speziato",
    "Families": { "MUSCHIATO": 65, "LEGNOSO": 30, "SPEZIATO CALDO": 5 },
    "Volatility": "Cuore"
  },
  "CANNELLA FOGLIE SENZA SAFROLO": {
    "CAS": "84649-98-9",
    "Type": "Materia Prima",
    "IFRA": 0.6,
    "MinUsage": 0.05,
    "MaxUsage": 0.6,
    "AverageUsage": 0.2,
    "CostPerGram": 0.45,
    "Notes": "Speziato, caldo, eugenolico",
    "Families": { "SPEZIATO CALDO": 100 },
    "Volatility": "Cuore"
  },
  "VANIGLIA MOU BASE": {
    "CAS": "#mix",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.00001,
    "BP": 320.0,
    "Impact": 180,
    "MinUsage": 0.5,
    "MaxUsage": 10.0,
    "AverageUsage": 4.0,
    "CostPerGram": 0.45,
    "Notes": "Gourmand, lattonico, dolce",
    "Families": { "VANIGLIATO": 100 },
    "Volatility": "Cuore, Fondo"
  },
  "JASMOPHORE": {
    "CAS": "-",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0008,
    "BP": 280.0,
    "Impact": 220,
    "MinUsage": 1.0,
    "MaxUsage": 15.0,
    "AverageUsage": 5.0,
    "CostPerGram": 0.45,
    "Notes": "Base gelsomino, floreale ricco",
    "Families": { "FLOREALE BIANCO": 100 },
    "Volatility": "Cuore"
  },
  "ALDEIDE CICLAMINO": {
    "CAS": "103-95-7",
    "Type": "Materia Prima",
    "IFRA": 0.95,
    "VP": 0.0045,
    "BP": 270.0,
    "Impact": 600,
    "MinUsage": 0.1,
    "MaxUsage": 0.95,
    "AverageUsage": 0.8,
    "CostPerGram": 0.45,
    "Notes": "Fiorito fresco, verde, umido",
    "Families": { "FRESCO": 90, "VERDE": 10 },
    "Volatility": "Cuore"
  },
  "ASS. CACAO": {
    "CAS": "8002-31-1",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.00005,
    "BP": 330.0,
    "Impact": 250,
    "MinUsage": 0.1,
    "MaxUsage": 2.5,
    "AverageUsage": 1.0,
    "CostPerGram": 0.45,
    "Notes": "Cioccolato amaro, tostato",
    "Families": { "CIOCCOLATO": 90, "SPEZIATO CALDO": 10 },
    "Volatility": "Fondo"
  },
  "CALONE": {
    "CAS": "28940-11-6",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0013,
    "BP": 282.0,
    "Impact": 1000,
    "MinUsage": 0.01,
    "MaxUsage": 0.5,
    "AverageUsage": 0.2,
    "CostPerGram": 0.45,
    "Notes": "Marino, anguria, fresco",
    "Families": { "MARINO": 85, "FRESCO": 5, "SALATO": 5, "FRUTTATO": 5 },
    "Volatility": "Testa, Cuore"
  },
  "BICYCLONONALACTONE (IFF)": {
    "CAS": "4430-31-3",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0016,
    "BP": 305.0,
    "Impact": 120,
    "MinUsage": 0.2,
    "MaxUsage": 4.0,
    "AverageUsage": 1.0,
    "CostPerGram": 0.45,
    "Notes": "Cocco, lattonico, cremoso",
    "Families": { "LATTONICO": 30, "DOLCE": 60, "COCCO": 10 },
    "Volatility": "Fondo"
  },
  "VELOUTONE": {
    "CAS": "65443-14-3",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.015,
    "BP": 235.0,
    "Impact": 240,
    "MinUsage": 0.2,
    "MaxUsage": 5.0,
    "AverageUsage": 1.5,
    "CostPerGram": 0.45,
    "Notes": "Pesca, fruttato vellutato",
    "Families": { "FRUTTATO": 90, "DOLCE": 10 },
    "Volatility": "Testa"
  },
  "MIRTILLO NERO BASE": {
    "CAS": "-",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.05,
    "BP": 215.0,
    "Impact": 310,
    "MinUsage": 0.5,
    "MaxUsage": 6.0,
    "AverageUsage": 2.0,
    "CostPerGram": 0.45,
    "Notes": "Fruttato bosco, acidulo",
    "Families": { "FRUTTATO": 100 },
    "Volatility": "Testa"
  },
  "CLONAL": {
    "CAS": "2437-25-4",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.22,
    "BP": 198.0,
    "Impact": 940,
    "MinUsage": 0.01,
    "MaxUsage": 0.3,
    "AverageUsage": 0.05,
    "CostPerGram": 0.45,
    "Notes": "Zest di mandarino, metallico",
    "Families": { "AGRUMATO": 90, "FRESCO": 10 },
    "Volatility": "Testa"
  },
  "TONALID": {
    "CAS": "21145-77-7",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0003,
    "BP": 348.0,
    "Impact": 90,
    "MinUsage": 0.5,
    "MaxUsage": 15.0,
    "AverageUsage": 5.0,
    "CostPerGram": 0.45,
    "Notes": "Muschio bianco, pulito",
    "Families": { "MUSCHIATO": 100 },
    "Volatility": "Fondo"
  },
  "VANILLINA": {
    "CAS": "121-33-5",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.00018,
    "BP": 285.0,
    "Impact": 210,
    "MinUsage": 0.1,
    "MaxUsage": 5.0,
    "AverageUsage": 2.0,
    "CostPerGram": 0.45,
    "Notes": "Dolce, vaniglia pura",
    "Families": { "VANIGLIATO": 20, "DOLCE": 80 },
    "Volatility": "Cuore"
  },
  "ALDEIDE C-11 MOA": {
    "CAS": "19009-56-4",
    "Type": "Materia Prima",
    "IFRA": 0.2,
    "VP": 0.06,
    "BP": 224.0,
    "Impact": 1500,
    "MinUsage": 0.01,
    "MaxUsage": 0.2,
    "AverageUsage": 0.05,
    "CostPerGram": 0.45,
    "Notes": "Aldeidico, ceroso, agrumato",
    "Families": { "AGRUMATO": 60, "FRESCO": 40 },
    "Volatility": "Testa, Cuore"
  },
  "CORIANDOLO": {
    "CAS": "8008-52-4",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.15,
    "BP": 194.0,
    "Impact": 780,
    "MinUsage": 0.1,
    "MaxUsage": 2.0,
    "AverageUsage": 0.5,
    "CostPerGram": 0.45,
    "Notes": "Speziato fresco, agrumato",
    "Families": { "SPEZIATO FRESCO": 95, "AGRUMATO": 5 },
    "Volatility": "Testa"
  },
  "ALGENONE SP": {
    "CAS": "-",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0008,
    "BP": 295.0,
    "Impact": 1000,
    "MinUsage": 0.05,
    "MaxUsage": 2.0,
    "AverageUsage": 0.5,
    "CostPerGram": 0.45,
    "Notes": "Marino algale, salino",
    "Families": { "SALATO": 60, "MARINO": 35, "AROMATICO": 5 },
    "Volatility": "Cuore,Fondo"
  },
"SILVIAL": {
    "CAS": "6658-48-6",
    "Type": "Materia Prima",
    "IFRA": 0.1,
    "VP": 0.003,
    "BP": 281.0,
    "Impact": 280,
    "MinUsage": 0.05,
    "MaxUsage": 0.1,
    "AverageUsage": 0.08,
    "CostPerGram": 0.45,
    "Notes": "Mughetto, fiorito fresco",
    "Families": { "FLOREALE": 50, "FRESCO": 50 },
    "Volatility": "Cuore"
  },
  "FRUCTONE": {
    "CAS": "6413-10-1",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.12,
    "BP": 204.0,
    "Impact": 320,
    "MinUsage": 0.1,
    "MaxUsage": 10.0,
    "AverageUsage": 2.0,
    "CostPerGram": 0.45,
    "Notes": "Mela verde, fruttato fresco",
    "Families": { "FRUTTATO": 100 },
    "Volatility": "Testa"
  },
  "HEDIONE": {
    "CAS": "24851-98-7",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.00065,
    "BP": 310.0,
    "Impact": 45,
    "MinUsage": 2.0,
    "MaxUsage": 35.0,
    "AverageUsage": 12.0,
    "CostPerGram": 0.45,
    "Notes": "Gelsomino trasparente",
    "Families": { "FLOREALE": 90, "FRESCO": 10 },
    "Volatility": "Fondo"
  },
  "APHERMATE": {
    "CAS": "25225-08-5",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.045,
    "BP": 232.0,
    "Impact": 320,
    "MinUsage": 0.2,
    "MaxUsage": 6.0,
    "AverageUsage": 3.0,
    "CostPerGram": 0.45,
    "Notes": "Marino, ozonico, fresco",
    "Families": { "FRESCO": 65, "OZONICO": 30, "FRUTTATO": 5 },
    "Volatility": "Testa"
  },
  "MELONAL": {
    "CAS": "106-72-9",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.18,
    "BP": 182.0,
    "Impact": 880,
    "MinUsage": 0.01,
    "MaxUsage": 0.5,
    "AverageUsage": 0.2,
    "CostPerGram": 0.45,
    "Notes": "Melone, cetriolo, fresco",
    "Families": { "ACQUATICO": 80, "FRESCO": 20 },
    "Volatility": "Testa"
  },
  "ZAFFERANO ACCORDO": {
    "CAS": "-",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0004,
    "BP": 315.0,
    "Impact": 380,
    "MinUsage": 0.1,
    "MaxUsage": 3.0,
    "AverageUsage": 1.0,
    "CostPerGram": 0.45,
    "Notes": "Speziato cuoiato, caldo",
    "Families": { "SPEZIATO CALDO": 70, "CUOIATO": 30 },
    "Volatility": "Fondo"
  },
  "BASILICO": {
    "CAS": "-",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.1,
    "BP": 209.0,
    "Impact": 350,
    "MinUsage": 0.05,
    "MaxUsage": 2.5,
    "AverageUsage": 0.8,
    "CostPerGram": 0.45,
    "Notes": "Aromatico verde, anice",
    "Families": { "VERDE": 90, "SPEZIATO FRESCO": 10 },
    "Volatility": "Testa"
  },
  "VANIGLIA FRANCESE BASE": {
    "CAS": "#mix",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.00001,
    "BP": 312.0,
    "Impact": 160,
    "MinUsage": 1.0,
    "MaxUsage": 12.0,
    "AverageUsage": 4.0,
    "CostPerGram": 0.45,
    "Notes": "Vaniglia cremosa, custardy",
    "Families": { "VANIGLIATO": 100 },
    "Volatility": "Fondo"
  },
  "APPLE OLIFFAC BASE IFF": {
    "CAS": "-",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.08,
    "BP": 218.0,
    "Impact": 420,
    "MinUsage": 0.5,
    "MaxUsage": 8.0,
    "AverageUsage": 4.0,
    "CostPerGram": 0.45,
    "Notes": "Mela rossa succosa",
    "Families": { "MELA": 100 },
    "Volatility": "Testa"
  },
  "MANGO ACCORDO": {
    "CAS": "-",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.03,
    "BP": 258.0,
    "Impact": 450,
    "MinUsage": 0.5,
    "MaxUsage": 7.0,
    "AverageUsage": 3.0,
    "CostPerGram": 0.45,
    "Notes": "Fruttato tropicale esotico",
    "Families": { "TROPICALE": 70, "FRUTTATO": 30 },
    "Volatility": "Cuore"
  },
  "VANIGLIA BOURBON": {
    "CAS": "8024-06-4",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.00001,
    "BP": 305.0,
    "Impact": 180,
    "MinUsage": 0.1,
    "MaxUsage": 6.0,
    "AverageUsage": 2.0,
    "CostPerGram": 0.45,
    "Notes": "Vaniglia ricca, speziata, profonda",
    "Families": { "VANIGLIATO": 100 },
    "Volatility": "Fondo"
  },
  "AGARWOOD RICOSTRUITO": {
    "CAS": "-",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.00008,
    "BP": 380.0,
    "Impact": 410,
    "MinUsage": 0.1,
    "MaxUsage": 5.0,
    "AverageUsage": 2.0,
    "CostPerGram": 0.45,
    "Notes": "Oud, legnoso, animale, fumoso",
    "Families": { "OUD": 100 },
    "Volatility": "Fondo"
  },
  "BACDANOL": {
    "CAS": "28219-61-6",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0001,
    "BP": 333.0,
    "Impact": 150,
    "MinUsage": 0.5,
    "MaxUsage": 10.0,
    "AverageUsage": 4.0,
    "CostPerGram": 0.45,
    "Notes": "Sandalo cremoso, potente",
    "Families": { "LEGNOSO": 80, "LATTONICO": 20 },
    "Volatility": "Fondo"
  },
  "DELTA DECA-LACTONE": {
    "CAS": "705-86-2",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0007,
    "BP": 272.0,
    "Impact": 210,
    "MinUsage": 0.05,
    "MaxUsage": 2.0,
    "AverageUsage": 0.5,
    "CostPerGram": 0.45,
    "Notes": "Cremosità, cocco, latte",
    "Families": { "FRUTTATO": 60, "LATTONICO": 30, "COCCO": 10 },
    "Volatility": "Cuore"
  },
  "ALLYL AMYL GLYCOLATE": {
    "CAS": "67634-00-8",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.35,
    "BP": 190.0,
    "Impact": 820,
    "MinUsage": 0.02,
    "MaxUsage": 1.5,
    "AverageUsage": 0.5,
    "CostPerGram": 0.45,
    "Notes": "Ananas moderno, metallico",
    "Families": { "TROPICALE": 90, "FRUTTATO": 10 },
    "Volatility": "Testa"
  },
  "GEOSMINA": {
    "CAS": "23333-91-7",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.01,
    "BP": 271.0,
    "Impact": 1000,
    "MinUsage": 0.001,
    "MaxUsage": 0.05,
    "AverageUsage": 0.01,
    "CostPerGram": 0.45,
    "Notes": "Terra bagnata, pioggia (usare diluita)",
    "Families": { "TERROSO": 20, "ACQUATICO": 80 },
    "Volatility": "Testa, Cuore"
  },
  "GAMMA DECA-LACTONE": {
    "CAS": "706-14-9",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0006,
    "BP": 281.0,
    "Impact": 190,
    "MinUsage": 0.1,
    "MaxUsage": 3.0,
    "AverageUsage": 0.8,
    "CostPerGram": 0.45,
    "Notes": "Pesca, albicocca, lattonico",
    "Families": { "FRUTTATO": 80, "LATTONICO": 20 },
    "Volatility": "Cuore"
  },
  "AMYL SALICYLATE": {
    "CAS": "2050-08-0",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.018,
    "BP": 277.0,
    "Impact": 140,
    "MinUsage": 0.5,
    "MaxUsage": 10.0,
    "AverageUsage": 4.0,
    "CostPerGram": 0.45,
    "Notes": "Fiorito, erba, orchidea",
    "Families": { "AROMATICO": 50, "VERDE": 20, "ERBACEO": 20, "SALATO": 10 },
    "Volatility": "Cuore"
  },
  "ROSMARINO": {
    "CAS": "8000-25-7",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.25,
    "BP": 178.0,
    "Impact": 500,
    "MinUsage": 0.05,
    "MaxUsage": 1.5,
    "AverageUsage": 0.5,
    "CostPerGram": 0.45,
    "Notes": "Erbaceo fresco, canforaceo",
    "Families": { "ERBACEO": 20, "VERDE": 50, "AROMATICO": 30 },
    "Volatility": "Testa"
  },
  "GLYCOLIERRAL": {
    "CAS": "94087-23-7",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.002,
    "BP": 302.0,
    "Impact": 210,
    "MinUsage": 0.1,
    "MaxUsage": 4.0,
    "AverageUsage": 0.6,
    "CostPerGram": 0.45,
    "Notes": "Verde edera, legnoso fresco",
    "Families": { "VERDE": 80, "AROMATICO": 20 },
    "Volatility": "Fondo"
  },
  "TERRANOL": {
    "CAS": "88644-30-8",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0009,
    "BP": 285.0,
    "Impact": 890,
    "MinUsage": 0.01,
    "MaxUsage": 0.5,
    "AverageUsage": 0.1,
    "CostPerGram": 0.45,
    "Notes": "Terroso, muschio quercia, fango",
    "Families": { "TERROSO": 90, "LEGNOSO": 10 },
    "Volatility": "Cuore"
  },
  "MANZANATE (GIVAUDAN)": {
    "CAS": "39255-32-8",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.28,
    "BP": 174.0,
    "Impact": 910,
    "MinUsage": 0.01,
    "MaxUsage": 0.4,
    "AverageUsage": 0.1,
    "CostPerGram": 0.45,
    "Notes": "Mela verde, ananas, fruttato",
    "Families": { "FRUTTATO": 70, "TROPICALE": 30 },
    "Volatility": "Testa"
  },
  "RUM ACCORDO II": {
    "CAS": "-",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.4,
    "BP": 175.0,
    "Impact": 350,
    "MinUsage": 0.5,
    "MaxUsage": 8.0,
    "AverageUsage": 3.0,
    "CostPerGram": 0.45,
    "Notes": "Alcolico, boozy, dolce",
    "Families": { "RUM": 100 },
    "Volatility": "Testa"
  },
  "PHENETHYL PHENYL ACETATE": {
    "CAS": "102-20-5",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.00001,
    "BP": 325.0,
    "Impact": 220,
    "MinUsage": 0.1,
    "MaxUsage": 5.0,
    "AverageUsage": 1.0,
    "CostPerGram": 0.45,
    "Notes": "Rosa, miele, polveroso",
    "Families": { "MIELATO": 90, "FLOREALE": 10 },
    "Volatility": "Fondo"
  },
  "PHENETHYL ALCHOL": {
    "CAS": "60-12-8",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.02,
    "BP": 219.0,
    "Impact": 120,
    "MinUsage": 1.0,
    "MaxUsage": 20.0,
    "AverageUsage": 5.0,
    "CostPerGram": 0.45,
    "Notes": "Rosa fresca, petali",
    "Families": { "ROSA": 50, "MIELATO": 50 },
    "Volatility": "Testa"
  },
  "PISTACHIO CREAM BOLD BASE": {
    "CAS": "-",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0001,
    "BP": 305.0,
    "Impact": 200,
    "MinUsage": 0.5,
    "MaxUsage": 10.0,
    "AverageUsage": 4.0,
    "CostPerGram": 0.45,
    "Notes": "Pistacchio, nocciola, cremoso",
    "Families": { "LATTONICO": 40, "SPEZIATO CALDO": 60 },
    "Volatility": "Fondo"
  },
  "CANTHOXAL": {
    "CAS": "5462-06-6",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0035,
    "BP": 285.0,
    "Impact": 310,
    "MinUsage": 0.05,
    "MaxUsage": 2.5,
    "AverageUsage": 0.5,
    "CostPerGram": 0.45,
    "Notes": "Anice, finocchio, floreale",
    "Families": { "FLOREALE": 25, "ACQUATICO": 50, "SPEZIATO FRESCO": 10, "SPEZIATO CALDO": 10 },
    "Volatility": "Cuore"
  },
  "TERRASOL 2-ETHYL FENCHOL": {
    "CAS": "18368-91-7",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.04,
    "BP": 225.0,
    "Impact": 920,
    "MinUsage": 0.01,
    "MaxUsage": 0.5,
    "AverageUsage": 0.1,
    "CostPerGram": 0.45,
    "Notes": "Terroso, radici, minerale",
    "Families": { "TERROSO": 70, "SALATO": 10, "LEGNOSO": 20 },
    "Volatility": "Testa"
  },
  "BENZOINO O.E.": {
    "CAS": "9000-72-0",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.00001,
    "BP": 344.0,
    "Impact": 150,
    "MinUsage": 0.2,
    "MaxUsage": 8.0,
    "AverageUsage": 3.0,
    "CostPerGram": 0.45,
    "Notes": "Resinoso, vanigliato, balsamico",
    "Families": { "DOLCE": 50, "AMBRATO": 25, "VANIGLIATO": 25 },
    "Volatility": "Fondo"
  },
  "FLORALOZONE": {
    "CAS": "67634-14-4",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.012,
    "BP": 255.0,
    "Impact": 600,
    "MinUsage": 0.1,
    "MaxUsage": 3.5,
    "AverageUsage": 0.8,
    "CostPerGram": 0.45,
    "Notes": "Ozonico, fiorito, aria fresca",
    "Families": { "OZONICO": 80, "MARINO": 20 },
    "Volatility": "Cuore"
  },
  "FURFURYL MERCAPTAN": {
    "CAS": "98-02-2",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.75,
    "BP": 160.0,
    "Impact": 1500,
    "MinUsage": 0.0001,
    "MaxUsage": 0.01,
    "AverageUsage": 0.001,
    "CostPerGram": 0.45,
    "Notes": "Caffè tostato, zolfo (potentissimo)",
    "Families": { "SPEZIATO CALDO": 60, "FUMOSO": 40 },
    "Volatility": "Testa, Cuore"
  },
  "ABETE SIBERIANO": {
    "CAS": "91697-89-1",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.3,
    "BP": 172.0,
    "Impact": 320,
    "MinUsage": 0.1,
    "MaxUsage": 5.0,
    "AverageUsage": 1.0,
    "CostPerGram": 0.45,
    "Notes": "Pino, resinoso, aghi freschi",
    "Families": { "FRESCO": 80, "SPEZIATO FRESCO": 20 },
    "Volatility": "Testa"
  },
  "OCIMUM BASILICUM HERB OIL": {
    "CAS": "8015-73-4",
    "Type": "Materia Prima",
    "IFRA": 0.1,
    "VP": 0.08,
    "BP": 215.0,
    "Impact": 340,
    "MinUsage": 0.01,
    "MaxUsage": 0.1,
    "AverageUsage": 0.05,
    "CostPerGram": 0.45,
    "Notes": "Basilico aromatico, erbaceo",
    "Families": { "VERDE": 60, "AROMATICO": 30, "ERBACEO": 20 },
    "Volatility": "Testa"
  },
  "TIMO ROSSO": {
    "CAS": "8007-46-3",
    "Type": "Materia Prima",
    "IFRA": 0.5,
    "VP": 0.15,
    "BP": 233.0,
    "Impact": 410,
    "MinUsage": 0.01,
    "MaxUsage": 0.5,
    "AverageUsage": 0.1,
    "CostPerGram": 0.45,
    "Notes": "Aromatico, medicinale, caldo",
    "Families": { "AROMATICO": 60, "SALATO": 40 },
    "Volatility": "Testa"
  },
  "CITRONELLYL ACETATE": {
    "CAS": "150-84-5",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.03,
    "BP": 229.0,
    "Impact": 180,
    "MinUsage": 0.1,
    "MaxUsage": 10.0,
    "AverageUsage": 1.5,
    "CostPerGram": 0.45,
    "Notes": "Rosa, geranio, agrumato",
    "Families": { "ROSA": 50, "AGRUMATO": 10, "FLOREALE": 40 },
    "Volatility": "Testa"
  },
  "STRAWBERRY GLYCIDATE 1 (ALDEIDE C-16)": {
    "CAS": "77-83-8",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.001,
    "BP": 275.0,
    "Impact": 1800,
    "MinUsage": 0.1,
    "MaxUsage": 6.0,
    "AverageUsage": 1.5,
    "CostPerGram": 0.45,
    "Notes": "Fragola, fruttato dolce",
    "Families": { "FRUTTATO": 80, "DOLCE": 20 },
    "Volatility": "Cuore"
  },
  "EBANOL": {
    "CAS": "67801-20-1",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0003,
    "BP": 298.0,
    "Impact": 280,
    "MinUsage": 0.1,
    "MaxUsage": 8.0,
    "AverageUsage": 1.5,
    "CostPerGram": 0.45,
    "Notes": "Sandalo scuro, intenso",
    "Families": { "LEGNOSO": 90, "LATTONICO": 10 },
    "Volatility": "Fondo"
  },
  "OUD ROYAL ACCORDO": {
    "CAS": "-",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.00005,
    "BP": 375.0,
    "Impact": 480,
    "MinUsage": 0.1,
    "MaxUsage": 10.0,
    "AverageUsage": 2.5,
    "CostPerGram": 0.45,
    "Notes": "Legnoso nobile, orientale",
    "Families": { "OUD": 100 },
    "Volatility": "Fondo"
  },
  "LEGNO DI CEDRO VIRGINIA": {
    "CAS": "8000-27-9",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.01,
    "BP": 265.0,
    "Impact": 140,
    "MinUsage": 0.5,
    "MaxUsage": 20.0,
    "AverageUsage": 3.0,
    "CostPerGram": 0.45,
    "Notes": "Matita, legnoso secco",
    "Families": { "LEGNOSO": 100 },
    "Volatility": "Cuore"
  },
  "FILBERTONE": {
    "CAS": "81925-81-7",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.35,
    "BP": 170.0,
    "Impact": 960,
    "MinUsage": 0.001,
    "MaxUsage": 0.2,
    "AverageUsage": 0.01,
    "CostPerGram": 0.45,
    "Notes": "Nocciola tostata, metallico",
    "Families": { "CIOCCOLATO": 100 },
    "Volatility": "Testa"
  },
  "HONEY PROVENCE FIRABS": {
    "CAS": "-",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.00008,
    "BP": 330.0,
    "Impact": 420,
    "MinUsage": 0.1,
    "MaxUsage": 5.0,
    "AverageUsage": 0.8,
    "CostPerGram": 0.45,
    "Notes": "Miele naturale, cera d'api",
    "Families": { "MIELATO": 100 },
    "Volatility": "Fondo"
  },
  "FOGLIE DI LIME BASE": {
    "CAS": "-",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.2,
    "BP": 185.0,
    "Impact": 1200,
    "MinUsage": 0.1,
    "MaxUsage": 3.0,
    "AverageUsage": 1.0,
    "CostPerGram": 0.45,
    "Notes": "Verde citrico, croccante",
    "Families": { "AGRUMATO": 80, "VERDE": 20 },
    "Volatility": "Testa"
  },
  "CATRAME DI BETULLA": {
    "CAS": "8001-88-5",
    "Type": "Materia Prima",
    "IFRA": 0.1,
    "VP": 0.0005,
    "BP": 355.0,
    "Impact": 5000,
    "MinUsage": 0.005,
    "MaxUsage": 0.1,
    "AverageUsage": 0.02,
    "CostPerGram": 0.45,
    "Notes": "Fumoso, cuoio, bruciato",
    "Families": { "FUMOSO": 90, "CUOIATO": 10 },
    "Volatility": "Fondo"
  },
  "TIARE": {
    "CAS": "683748-01-8",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0006,
    "BP": 310.0,
    "Impact": 260,
    "MinUsage": 0.5,
    "MaxUsage": 10.0,
    "AverageUsage": 2.0,
    "CostPerGram": 0.45,
    "Notes": "Monoi, fiorito esotico, solare",
    "Families": { "FLOREALE BIANCO": 90, "TROPICALE": 10 },
    "Volatility": "Fondo"
  },
  "NORLIMBANOL": {
    "CAS": "70788-30-6",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0001,
    "BP": 340.0,
    "Impact": 1200,
    "MinUsage": 0.05,
    "MaxUsage": 3.0,
    "AverageUsage": 0.5,
    "CostPerGram": 0.45,
    "Notes": "Legnoso secco estremo, ambrato, vibrante",
    "Families": { "AMBRATO": 80, "LEGNOSO": 20 },
    "Volatility": "Fondo"
  },
  "DATTERI": {
    "CAS": "68039-69-0",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0008,
    "BP": 315.0,
    "Impact": 290,
    "MinUsage": 0.5,
    "MaxUsage": 10.0,
    "AverageUsage": 3.0,
    "CostPerGram": 0.45,
    "Notes": "Fruttato dolce, sciropposo, gourmand",
    "Families": { "FRUTTATO": 60, "DOLCE": 35, "FUMOSO": 5 },
    "Volatility": "Fondo"
  },
  "LILLA": {
    "CAS": "80-54-6",
    "Type": "Materia Prima",
    "IFRA": 0.2,
    "VP": 0.006,
    "BP": 282.0,
    "Impact": 180,
    "MinUsage": 0.1,
    "MaxUsage": 0.2,
    "AverageUsage": 0.15,
    "CostPerGram": 0.45,
    "Notes": "Fiorito dolce, polveroso, primaverile",
    "Families": { "FLOREALE": 60, "FRESCO": 40 },
    "Volatility": "Cuore"
  },
  "SANDALWOOD OIL INDIAN": {
    "CAS": "8006-87-9",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.00005,
    "BP": 302.0,
    "Impact": 140,
    "MinUsage": 0.5,
    "MaxUsage": 10.0,
    "AverageUsage": 2.5,
    "CostPerGram": 0.45,
    "Notes": "Sandalo naturale, cremoso, lattonico",
    "Families": { "LEGNOSO": 80, "LATTONICO": 20 },
    "Volatility": "Fondo"
  },
  "SCENTENAL": {
    "CAS": "86803-90-9",
    "Type": "Materia Prima",
    "IFRA": 0.1,
    "VP": 0.035,
    "BP": 242.0,
    "Impact": 1000,
    "MinUsage": 0.01,
    "MaxUsage": 0.1,
    "AverageUsage": 0.05,
    "CostPerGram": 0.45,
    "Notes": "Marino, ozonico, verde foglie",
    "Families": { "OZONICO": 40, "MARINO": 30, "SALATO": 30 },
    "Volatility": "Testa, Cuore"
  },
  "ISO E SUPER": {
    "CAS": "54464-57-2",
    "Type": "Materia Prima",
    "IFRA": 20.0,
    "VP": 0.0018,
    "BP": 300.0,
    "Impact": 200,
    "MinUsage": 1.0,
    "MaxUsage": 20.0,
    "AverageUsage": 12.0,
    "CostPerGram": 0.45,
    "Notes": "Vellutato, cedrino, ambrato",
    "Families": { "LEGNOSO": 70, "AMBRATO": 30 },
    "Volatility": "Fondo"
  },
  "MELOGRANO BASE": {
    "CAS": "-",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.05,
    "BP": 210.0,
    "Impact": 310,
    "MinUsage": 0.5,
    "MaxUsage": 8.0,
    "AverageUsage": 3.0,
    "CostPerGram": 0.45,
    "Notes": "Fruttato rosso, acidulo, fresco",
    "Families": { "FRUTTATO": 100 },
    "Volatility": "Testa"
  },
  "HABANOLIDE": {
    "CAS": "111879-80-2",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.00015,
    "BP": 335.0,
    "Impact": 110,
    "MinUsage": 1.0,
    "MaxUsage": 30.0,
    "AverageUsage": 5.0,
    "CostPerGram": 0.45,
    "Notes": "Muschio metallico, pulito, ceroso",
    "Families": { "MUSCHIATO": 100 },
    "Volatility": "Fondo"
  },
  "GAMMA TERPINENE": {
    "CAS": "99-85-4",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 1.1,
    "BP": 182.0,
    "Impact": 240,
    "MinUsage": 0.1,
    "MaxUsage": 5.0,
    "AverageUsage": 1.0,
    "CostPerGram": 0.45,
    "Notes": "Agrumato, erbaceo, limone",
    "Families": { "AGRUMATO": 60, "ERBACEO": 30, "FRESCO": 10 },
    "Volatility": "Testa"
  },
  "DECANAL (ALDEIDE C-10)": {
    "CAS": "112-31-2",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.18,
    "BP": 208.0,
    "Impact": 2000,
    "MinUsage": 0.01,
    "MaxUsage": 1.0,
    "AverageUsage": 0.1,
    "CostPerGram": 0.45,
    "Notes": "Buccia d'arancia, aldeidico, potente",
    "Families": { "AGRUMATO": 100 },
    "Volatility": "Testa, Cuore"
  },
  "BENZYL BENZOATE": {
    "CAS": "120-51-4",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0003,
    "BP": 323.0,
    "Impact": 10,
    "MinUsage": 1.0,
    "MaxUsage": 100.0,
    "AverageUsage": 10.0,
    "CostPerGram": 0.45,
    "Notes": "Fissativo quasi inodore, solvente",
    "Families": { "FLOREALE": 100 },
    "Volatility": "Fondo"
  },
  "SALVIA SCLAREA": {
    "CAS": "8016-63-5",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.02,
    "BP": 209.0,
    "Impact": 350,
    "MinUsage": 0.05,
    "MaxUsage": 3.0,
    "AverageUsage": 0.5,
    "CostPerGram": 0.45,
    "Notes": "Erbaceo, ambrato, aromatico",
    "Families": { "ERBACEO": 30, "AROMATICO": 70 },
    "Volatility": "Testa"
  },
  "CUMARINA": {
    "CAS": "91-64-5",
    "Type": "Materia Prima",
    "IFRA": 1.6,
    "VP": 0.00013,
    "BP": 301.0,
    "Impact": 480,
    "MinUsage": 0.05,
    "MaxUsage": 1.6,
    "AverageUsage": 0.8,
    "CostPerGram": 0.45,
    "Notes": "Fieno appena tagliato, mandorla dolce",
    "Families": { "DOLCE": 80, "SPEZIATO CALDO": 20 },
    "Volatility": "Fondo"
  },
  "CIS-3-HEXENYL SALICYLATE": {
    "CAS": "65405-77-8",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0007,
    "BP": 271.0,
    "Impact": 140,
    "MinUsage": 0.5,
    "MaxUsage": 10.0,
    "AverageUsage": 1.5,
    "CostPerGram": 0.45,
    "Notes": "Verde, fiorito, solare",
    "Families": { "AROMATICO": 35, "VERDE": 35, "SALATO": 30 },
    "Volatility": "Cuore"
  },
  "QUERCUS ROBUR WOOD EXTRACT": {
    "CAS": "71011-28-4",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.00005,
    "BP": 360.0,
    "Impact": 190,
    "MinUsage": 0.1,
    "MaxUsage": 4.0,
    "AverageUsage": 0.5,
    "CostPerGram": 0.45,
    "Notes": "Legnoso quercia, boozy, vanigliato",
    "Families": { "RUM": 50, "LEGNOSO": 45, "DOLCE": 5 },
    "Volatility": "Fondo"
  },
  "ROSE GIVCO 217": {
    "CAS": "-",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.015,
    "BP": 245.0,
    "Impact": 380,
    "MinUsage": 1.0,
    "MaxUsage": 25.0,
    "AverageUsage": 4.0,
    "CostPerGram": 0.45,
    "Notes": "Base rosa ricca e completa",
    "Families": { "ROSA": 100 },
    "Volatility": "Cuore"
  },
  "ALLYL HEXANOATE": {
    "CAS": "123-68-2",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.38,
    "BP": 185.0,
    "Impact": 420,
    "MinUsage": 0.01,
    "MaxUsage": 2.0,
    "AverageUsage": 0.2,
    "CostPerGram": 0.45,
    "Notes": "Ananas, fruttato tropicale",
    "Families": { "TROPICALE": 95, "FRUTTATO": 5 },
    "Volatility": "Testa"
  },
  "AMBROXAN": {
    "CAS": "6790-58-5",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.00015,
    "BP": 285.0,
    "Impact": 500,
    "MinUsage": 0.05,
    "MaxUsage": 8.0,
    "AverageUsage": 1.0,
    "CostPerGram": 0.45,
    "Notes": "Ambrato, pulito, fissativo eccellente",
    "Families": { "AMBRATO": 60, "MUSCHIATO": 30, "MARINO": 10 },
    "Volatility": "Cuore, Fondo"
  },
  "HERBANATE (GIVAUDAN)": {
    "CAS": "116126-82-0",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.02,
    "BP": 240.0,
    "Impact": 280,
    "MinUsage": 0.1,
    "MaxUsage": 5.0,
    "AverageUsage": 1.0,
    "CostPerGram": 0.45,
    "Notes": "Erbaceo, fruttato mela/banana",
    "Families": { "ERBACEO": 70, "FRUTTATO": 20, "TROPICALE": 10 },
    "Volatility": "Testa"
  },
  "ANISIC ALDEHYDE": {
    "CAS": "123-11-5",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.002,
    "BP": 248.0,
    "Impact": 240,
    "MinUsage": 0.1,
    "MaxUsage": 10.0,
    "AverageUsage": 1.5,
    "CostPerGram": 0.45,
    "Notes": "Biancospino, anice, dolce",
    "Families": { "SPEZIATO CALDO": 25, "DOLCE": 75 },
    "Volatility": "Cuore"
  },
  "IONONE ALFA": {
    "CAS": "127-41-3",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.01,
    "BP": 259.0,
    "Impact": 310,
    "MinUsage": 0.1,
    "MaxUsage": 10.0,
    "AverageUsage": 1.2,
    "CostPerGram": 0.45,
    "Notes": "Violetta, fiorito, polveroso",
    "Families": { "VIOLETTA": 30, "FLOREALE": 70 },
    "Volatility": "Cuore"
  },
  "ALCOL PROFUMIERE 96%": {
    "CAS": "64-17-5",
    "Type": "Solvente",
    "IFRA": 100.0,
    "VP": 5.9,
    "BP": 78.3,
    "Impact": 0,
    "MinUsage": 0.0,
    "MaxUsage": 100.0,
    "AverageUsage": 85.0,
    "CostPerGram": 0.02, 
    "Notes": "Vettore principale alcolico",
    "Families": { "SOLVENTE": 100 },
    "Volatility": "Testa"
  },
  "MUSK T (ETILENE BRASILLATE)": {
    "CAS": "105-95-3",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.00003,
    "BP": 332.0,
    "Impact": 110,
    "MinUsage": 0.5,
    "MaxUsage": 30.0,
    "AverageUsage": 10.0,
    "CostPerGram": 0.45,
    "Notes": "Muschio macrociclico, dolce, morbido",
    "Families": { "MUSCHIATO": 85, "DOLCE": 15 },
    "Volatility": "Fondo"
  },
  "STYRALLYL ACETATE": {
    "CAS": "93-92-5",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.25,
    "BP": 214.0,
    "Impact": 450,
    "MinUsage": 0.05,
    "MaxUsage": 2.5,
    "AverageUsage": 0.5,
    "CostPerGram": 0.45,
    "Notes": "Verde gardenia, rabarbaro",
    "Families": { "VERDE": 90, "AROMATICO": 10 },
    "Volatility": "Testa"
  },
  "PHENOXANOL": {
    "CAS": "55066-48-3",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0006,
    "BP": 311.0,
    "Impact": 180,
    "MinUsage": 0.1,
    "MaxUsage": 10.0,
    "AverageUsage": 3.0,
    "CostPerGram": 0.45,
    "Notes": "Rosa fresca, fiorito bianco",
    "Families": { "FLOREALE": 70, "FRESCO": 20, "ROSA": 10 },
    "Volatility": "Fondo"
  },
  "ALPHA-AMYL CINNAMALDHEYDE": {
    "CAS": "122-40-7",
    "Type": "Materia Prima",
    "IFRA": 1.4,
    "VP": 0.0001,
    "BP": 290.0,
    "Impact": 110,
    "MinUsage": 0.5,
    "MaxUsage": 1.4,
    "AverageUsage": 1.0,
    "CostPerGram": 0.45,
    "Notes": "Gelsomino oleoso, ceroso",
    "Families": { "FLOREALE": 75, "FLOREALE BIANCO": 25 },
    "Volatility": "Fondo"
  },
  "CIS-3-HEXENOL": {
    "CAS": "928-96-1",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 1.2,
    "BP": 156.0,
    "Impact": 850,
    "MinUsage": 0.01,
    "MaxUsage": 0.8,
    "AverageUsage": 0.2,
    "CostPerGram": 0.45,
    "Notes": "Erba tagliata, verde freschissimo",
    "Families": { "ERBACEO": 90, "FRESCO": 5, "VERDE": 5 },
    "Volatility": "Testa"
  },
  "ISOLONGIFOLANONE": {
    "CAS": "23787-90-8",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0005,
    "BP": 305.0,
    "Impact": 210,
    "MinUsage": 0.1,
    "MaxUsage": 15.0,
    "AverageUsage": 3.0,
    "CostPerGram": 0.45,
    "Notes": "Legnoso ambrato, secco",
    "Families": { "TERROSO": 80, "LEGNOSO": 20 },
    "Volatility": "Fondo"
  },
  "ADOXAL": {
    "CAS": "141-13-9",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.003,
    "BP": 268.0,
    "Impact": 880,
    "MinUsage": 0.01,
    "MaxUsage": 0.5,
    "AverageUsage": 0.1,
    "CostPerGram": 0.45,
    "Notes": "Ozonico fresco, lino, potente",
    "Families": { "OZONICO": 50, "FRESCO": 40, "ACQUATICO": 10 },
    "Volatility": "Cuore"
  },
  "HELIONAL": {
    "CAS": "1205-17-0",
    "Type": "Materia Prima",
    "IFRA": 1.1,
    "VP": 0.0003,
    "BP": 282.0,
    "Impact": 320,
    "MinUsage": 0.05,
    "MaxUsage": 1.1,
    "AverageUsage": 0.6,
    "CostPerGram": 0.45,
    "Notes": "Fiorito fresco, ozonico, fieno",
    "Families": { "ACQUATICO": 80, "OZONICO": 20 },
    "Volatility": "Fondo"
  },
  "CARAMELLO BASE": {
    "CAS": "-",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0001,
    "BP": 320.0,
    "Impact": 380,
    "MinUsage": 0.1,
    "MaxUsage": 5.0,
    "AverageUsage": 1.0,
    "CostPerGram": 0.45,
    "Notes": "Gourmand, zucchero bruciato",
    "Families": { "CARAMELLO": 100 },
    "Volatility": "Fondo"
  },
  "ETIL LINALOLO": {
    "CAS": "10339-55-6",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.1,
    "BP": 215.0,
    "Impact": 250,
    "MinUsage": 0.5,
    "MaxUsage": 20.0,
    "AverageUsage": 5.0,
    "CostPerGram": 0.45,
    "Notes": "Lavanda, bergamotto, fiorito fresco",
    "Families": { "FRESCO": 85, "AGRUMATO": 5, "FLOREALE": 10 },
    "Volatility": "Testa"
  },
  "VERAMOSS (IFF)": {
    "CAS": "4707-47-5",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0004,
    "BP": 315.0,
    "Impact": 450,
    "MinUsage": 0.05,
    "MaxUsage": 3.5,
    "AverageUsage": 0.8,
    "CostPerGram": 0.45,
    "Notes": "Muschio quercia moderno, mare",
    "Families": { "AROMATICO": 30, "MUSCHIATO": 30, "VERDE": 40 },
    "Volatility": "Fondo"
  },
  "BUTIRRATO ETILE": {
    "CAS": "105-54-4",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 15.3,
    "BP": 121.0,
    "Impact": 780,
    "MinUsage": 0.01,
    "MaxUsage": 1.0,
    "AverageUsage": 0.3,
    "CostPerGram": 0.45,
    "Notes": "Fruttato succoso, ananas, mela",
    "Families": { "FRUTTATO": 70, "TROPICALE": 30 },
    "Volatility": "Testa"
  },
  "CARDAMOMO": {
    "CAS": "8000-66-6",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.5,
    "BP": 188.0,
    "Impact": 800,
    "MinUsage": 0.05,
    "MaxUsage": 4.0,
    "AverageUsage": 0.5,
    "CostPerGram": 0.45,
    "Notes": "Speziato freddo, aromatico",
    "Families": { "SPEZIATO FRESCO": 70, "AGRUMATO": 20, "AROMATICO": 10 },
    "Volatility": "Testa"
  },
  "TRIETHYL CITRATE": {
    "CAS": "77-93-0",
    "Type": "Solvente",
    "IFRA": 100.0,
    "VP": 0.001,
    "BP": 294.0,
    "Impact": 0,
    "MinUsage": 0.1,
    "MaxUsage": 100.0,
    "AverageUsage": 5.0,
    "CostPerGram": 0.02,
    "Notes": "Solvente inodore, fissativo",
    "Families": {},
    "Volatility": "Fondo"
  },
  "VETIVER (VETIVERIA ZIZANIOIDE OIL)": {
    "CAS": "8016-96-4",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0001,
    "BP": 285.0,
    "Impact": 240,
    "MinUsage": 0.1,
    "MaxUsage": 8.0,
    "AverageUsage": 2.0,
    "CostPerGram": 0.45,
    "Notes": "Legnoso, terroso, radici, fumoso",
    "Families": { "LEGNOSO": 90, "FUMOSO": 10 },
    "Volatility": "Fondo"
  },
  "GAMMA-NONALACTONE (ALDEIDE C-18)": {
    "CAS": "104-61-0",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0015,
    "BP": 243.0,
    "Impact": 1800,
    "MinUsage": 0.05,
    "MaxUsage": 5.0,
    "AverageUsage": 1.5,
    "CostPerGram": 0.45,
    "Notes": "Cocco, cremoso, lattonico",
    "Families": { "COCCO": 100 },
    "Volatility": "Fondo"
  },
  "ETIL MALTOLO": {
    "CAS": "4940-11-8",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0005,
    "BP": 290.0,
    "Impact": 850,
    "MinUsage": 0.01,
    "MaxUsage": 5.0,
    "AverageUsage": 0.5,
    "CostPerGram": 0.45,
    "Notes": "Zucchero filato, fragola cotta",
    "Families": { "CARAMELLO": 75, "DOLCE": 25 },
    "Volatility": "Fondo"
  },
  "GALAXOLIDE": {
    "CAS": "1222-05-5",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0001,
    "BP": 330.0,
    "Impact": 120,
    "MinUsage": 1.0,
    "MaxUsage": 40.0,
    "AverageUsage": 10.0,
    "CostPerGram": 0.45,
    "Notes": "Muschio bianco pulito, floreale",
    "Families": { "MUSCHIATO": 100 },
    "Volatility": "Fondo"
  },
  "TIMBERSILK": {
    "CAS": "54464-57-2",
    "Type": "Materia Prima",
    "IFRA": 20.0,
    "VP": 0.0007,
    "BP": 295.0,
    "Impact": 70,
    "MinUsage": 1.0,
    "MaxUsage": 20.0,
    "AverageUsage": 8.0,
    "CostPerGram": 0.45,
    "Notes": "Versione arricchita dell'Iso E Super",
    "Families": { "LEGNOSO": 50, "AMBRATO": 50 },
    "Volatility": "Fondo"
  },
  "DPG DIPROPYLENE GLYCOL": {
    "CAS": "25265-71-8",
    "Type": "Solvente",
    "IFRA": 100.0,
    "VP": 0.01,
    "BP": 232.0,
    "Impact": 0,
    "MinUsage": 0.1,
    "MaxUsage": 100.0,
    "AverageUsage": 5.0,
    "CostPerGram": 0.02,
    "Notes": "Solvente standard inodore",
    "Families": {},
    "Volatility": "Fondo"
  },
  "METHYL LAITONE": {
    "CAS": "94201-19-1",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.01,
    "BP": 245.0,
    "Impact": 820,
    "MinUsage": 0.01,
    "MaxUsage": 1.5,
    "AverageUsage": 0.1,
    "CostPerGram": 0.45,
    "Notes": "Latte, cocco, cremosità estrema",
    "Families": { "LATTONICO": 100 },
    "Volatility": "Cuore"
  },
  "AMBER XTREME": {
    "CAS": "647828-16-8",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0001,
    "BP": 345.0,
    "Impact": 1500,
    "MinUsage": 0.001,
    "MaxUsage": 1.0,
    "AverageUsage": 0.05,
    "CostPerGram": 0.45,
    "Notes": "Ambrato secco, vibrante, radiante",
    "Families": { "AMBRATO": 100 },
    "Volatility": "Fondo"
  },
  "AMBROCENIDE": {
    "CAS": "211299-54-6",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.00008,
    "BP": 355.0,
    "Impact": 1000,
    "MinUsage": 0.001,
    "MaxUsage": 0.5,
    "AverageUsage": 0.03,
    "CostPerGram": 0.45,
    "Notes": "Legnoso ambrato, potentissimo, fissativo",
    "Families": { "AMBRATO": 80, "LEGNOSO": 15, "MARINO": 5 },
    "Volatility": "Testa, Cuore, Fondo"
  },
  "MARITIMA": {
    "CAS": "38462-23-6",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.1,
    "BP": 235.0,
    "Impact": 910,
    "MinUsage": 0.01,
    "MaxUsage": 1.0,
    "AverageUsage": 0.1,
    "CostPerGram": 0.45,
    "Notes": "Aria di mare, salino potente",
    "Families": { "SALATO": 20, "OZONICO": 30, "MARINO": 50 },
    "Volatility": "Cuore"
  },
  "METHYL ANTHRANILATE (ALDEIDE C-9)": { 
    "CAS": "124-19-6",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.5,
    "BP": 191.0,
    "Impact": 850,
    "MinUsage": 0.01,
    "MaxUsage": 1.5,
    "AverageUsage": 0.2,
    "CostPerGram": 0.45,
    "Notes": "Agrumato, ceroso, floreale",
    "Families": { "AGRUMATO": 100 },
    "Volatility": "Testa"
  },
  "FLOROL": {
    "CAS": "63500-71-0",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.002,
    "BP": 242.0,
    "Impact": 240,
    "MinUsage": 0.5,
    "MaxUsage": 20.0,
    "AverageUsage": 6.0,
    "CostPerGram": 0.45,
    "Notes": "Mughetto morbido, fiorito bianco",
    "Families": { "FLOREALE": 100 },
    "Volatility": "Cuore"
  },
  "VERTOFIX": {
    "CAS": "32388-55-9",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.0003,
    "BP": 301.0,
    "Impact": 310,
    "MinUsage": 0.5,
    "MaxUsage": 25.0,
    "AverageUsage": 5.0,
    "CostPerGram": 0.45,
    "Notes": "Legnoso cedro, ambrato, cuoiato",
    "Families": { "CUOIATO": 80, "LEGNOSO": 20 },
    "Volatility": "Fondo"
  },
  "ALFA_DAMASCONE": {
    "CAS": "24720-09-0",
    "Type": "Materia Prima",
    "IFRA": 0.02,
    "VP": 0.015,
    "BP": 255.0,
    "Impact": 880,
    "MinUsage": 0.001,
    "MaxUsage": 0.02,
    "AverageUsage": 0.01,
    "CostPerGram": 0.45,
    "Notes": "Rosa fruttata, mela, potente",
    "Families": { "FLOREALE": 50, "ROSA": 30, "FRUTTATO": 20 },
    "Volatility": "Cuore"
  },
  "AMBRINOL_S": {
    "CAS": "41199-19-3",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.001,
    "BP": 288.0,
    "Impact": 1400,
    "MinUsage": 0.005,
    "MaxUsage": 0.5,
    "AverageUsage": 0.1,
    "CostPerGram": 0.45,
    "Notes": "Ambrato animale, salino, potente",
    "Families": { "ANIMALICO": 50, "SALATO": 30, "MARINO": 20 },
    "Volatility": "Cuore, Fondo"
  },
  "RUM_ACCORDO_I": {
    "CAS": "8030-89-5",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 15.0,
    "BP": 85.0,
    "Impact": 550,
    "MinUsage": 0.1,
    "MaxUsage": 5.0,
    "AverageUsage": 1.0,
    "CostPerGram": 0.45,
    "Notes": "Alcolico Rum, caldo",
    "Families": { "RUM": 100 },
    "Volatility": "Testa"
  },
  "BENZYL SALICYLATE": {
    "CAS": "118-58-1",
    "Type": "Materia Prima",
    "IFRA": 6.2,
    "VP": 0.0003,
    "BP": 322.0,
    "Impact": 80.0,
    "MinUsage": 1.0,
    "MaxUsage": 15.0,
    "AverageUsage": 5.0,
    "CostPerGram": 0.45,
    "Notes": "Fissativo fiorito blando, solare",
    "Families": { "AROMATICO": 50, "FLOREALE": 30, "SALATO": 20 },
    "Volatility": "Fondo"
  },
  "BERGAMOTTO CALABRIA FCF": {
        "CAS": "8007-75-8",
        "Type": "Materia Prima",
        "IFRA": 100.0,
        "VP": 1.2,
        "BP": 176.0,
        "Impact": 100,
        "MinUsage": 0.05,
        "MaxUsage": 20.0,
        "AverageUsage": 5.0,
        "CostPerGram": 0.45,
        "Notes": "Agrumato nobile, fresco",
        "Families": {"AGRUMATO": 100},
        "Volatility": "Testa"  
  },
  "CASCALONE": {
    "CAS": "950919-28-5",
    "Type": "Materia Prima",
    "IFRA": 100.0,
    "VP": 0.015,
    "BP": 252.0,
    "Impact": 790,
    "MinUsage": 0.1,
    "MaxUsage": 5.0,
    "AverageUsage": 1.0,
    "Notes": "Marino, acquatico, fresco, ozonico",
    "Families": { "MARINO": 80, "ACQUATICO": 20 },
    "Volatility": "Cuore"
  }
};

export const FAMILY_COLORS: Record<string, string> = {
    "AGRUMATO": "#C3f53b",
    "AMBRATO": "#AB4502",
    "ANIMALICO": "#8B4513",
    "AROMATICO": "#2B5936",
    "CARAMELLO": "#CD853F",
    "LEGNOSO": "#381F0F",
    "MARINO": "#07108C",
    "FRUTTATO": "#FF2C00",
    "FLOREALE": "#B52F4A",
    "FLOREALE BIANCO": "#EDD5D8",
    "SALATO": "#F0F0F5",
    "SPEZIATO CALDO": "#822312",
    "SPEZIATO FRESCO": "#31A617",
    "ERBACEO": "#51824F",
    "FRESCO": "#91B5B5",
    "MUSCHIATO": "#D598FA",
    "VANIGLIATO": "#F5D793",
    "DOLCE": "#A82308",
    "RUM": "#591204",
    "ROSA": "#FC1729",
    "PATCHOULI": "#473F0C",
    "TROPICALE": "#E39102",
    "TERROSO": "#362C0A",
    "LATTONICO": "#EDE9E1",
    "OUD": "#302B17",
    "VERDE": "#0E9C09",
    "MELA": "#76E317",
    "MIELATO": "#F5AF00",
    "OZONICO": "#1DC4C4",
    "CIOCCOLATO": "#633D0D",
    "ACQUATICO": "#4061D6",
    "VIOLETTA": "#75014C",
    "CAFFE": "#593501",
    "DA DEFINIRE": "#808080"
};